from typing import List
from app.schemas.news import NewsSource


SOURCES: List[NewsSource] = [
    # BBC
    NewsSource(
        source="BBC",
        name="BBC News",
        url="https://feeds.bbci.co.uk/news/rss.xml",
        bias="center",
        owner="BBC",
        state_media=True,
        based="UK",
    ),
    NewsSource(
        source="BBC",
        name="BBC World",
        url="https://feeds.bbci.co.uk/news/world/rss.xml",
        bias="center",
        owner="BBC",
        state_media=True,
        based="UK",
    ),
    NewsSource(
        source="BBC",
        name="BBC Business",
        url="https://feeds.bbci.co.uk/news/business/rss.xml",
        bias="center",
        owner="BBC",
        state_media=True,
        based="UK",
    ),
    NewsSource(
        source="BBC",
        name="BBC Technology",
        url="https://feeds.bbci.co.uk/news/technology/rss.xml",
        bias="center",
        owner="BBC",
        state_media=True,
        based="UK",
    ),
    # CNN
    NewsSource(
        source="CNN",
        name="CNN",
        url="http://rss.cnn.com/rss/edition.rss",
        bias="leans-left",
        owner="Warner Bros. Discovery",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="CNN",
        name="CNN World",
        url="http://rss.cnn.com/rss/edition_world.rss",
        bias="leans-left",
        owner="Warner Bros. Discovery",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="CNN",
        name="CNN US",
        url="http://rss.cnn.com/rss/edition_us.rss",
        bias="leans-left",
        owner="Warner Bros. Discovery",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="CNN",
        name="CNN Business",
        url="http://rss.cnn.com/rss/money_news_international.rss",
        bias="leans-left",
        owner="Warner Bros. Discovery",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="CNN",
        name="CNN Technology",
        url="http://rss.cnn.com/rss/edition_technology.rss",
        bias="leans-left",
        owner="Warner Bros. Discovery",
        state_media=False,
        based="US",
    ),
    # Fox News
    NewsSource(
        source="Fox News",
        name="Fox News",
        url="https://moxie.foxnews.com/google-publisher/latest.xml",
        bias="right",
        owner="Fox Corporation",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="Fox News",
        name="Fox News World",
        url="https://moxie.foxnews.com/google-publisher/world.xml",
        bias="right",
        owner="Fox Corporation",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="Fox News",
        name="Fox News Politics",
        url="https://moxie.foxnews.com/google-publisher/politics.xml",
        bias="right",
        owner="Fox Corporation",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="Fox News",
        name="Fox News Science",
        url="https://moxie.foxnews.com/google-publisher/science.xml",
        bias="right",
        owner="Fox Corporation",
        state_media=False,
        based="US",
    ),
    NewsSource(
        source="Fox News",
        name="Fox News Tech",
        url="https://moxie.foxnews.com/google-publisher/tech.xml",
        bias="right",
        owner="Fox Corporation",
        state_media=False,
        based="US",
    ),
    # The Guardian
    NewsSource(
        source="The Guardian",
        name="The Guardian World",
        url="https://www.theguardian.com/world/rss",
        bias="left",
        owner="Scott Trust",
        state_media=False,
        based="UK",
    ),
    NewsSource(
        source="The Guardian",
        name="The Guardian UK",
        url="https://www.theguardian.com/uk-news/rss",
        bias="left",
        owner="Scott Trust",
        state_media=False,
        based="UK",
    ),
    NewsSource(
        source="The Guardian",
        name="The Guardian US",
        url="https://www.theguardian.com/us-news/rss",
        bias="left",
        owner="Scott Trust",
        state_media=False,
        based="UK",
    ),
    NewsSource(
        source="The Guardian",
        name="The Guardian Business",
        url="https://www.theguardian.com/business/rss",
        bias="left",
        owner="Scott Trust",
        state_media=False,
        based="UK",
    ),
    NewsSource(
        source="The Guardian",
        name="The Guardian Technology",
        url="https://www.theguardian.com/technology/rss",
        bias="left",
        owner="Scott Trust",
        state_media=False,
        based="UK",
    ),
    NewsSource(
        source="The Guardian",
        name="The Guardian Politics",
        url="https://www.theguardian.com/politics/rss",
        bias="left",
        owner="Scott Trust",
        state_media=False,
        based="UK",
    ),
    # NPR
    NewsSource(
        source="NPR",
        name="NPR News",
        url="https://feeds.npr.org/1001/rss.xml",
        bias="leans-left",
        owner="National Public Radio",
        state_media=True,
        based="US",
    ),
    NewsSource(
        source="NPR",
        name="NPR National",
        url="https://feeds.npr.org/1003/rss.xml",
        bias="leans-left",
        owner="National Public Radio",
        state_media=True,
        based="US",
    ),
    NewsSource(
        source="NPR",
        name="NPR World",
        url="https://feeds.npr.org/1004/rss.xml",
        bias="leans-left",
        owner="National Public Radio",
        state_media=True,
        based="US",
    ),
    NewsSource(
        source="NPR",
        name="NPR Business",
        url="https://feeds.npr.org/1006/rss.xml",
        bias="leans-left",
        owner="National Public Radio",
        state_media=True,
        based="US",
    ),
    NewsSource(
        source="NPR",
        name="NPR Technology",
        url="https://feeds.npr.org/1019/rss.xml",
        bias="leans-left",
        owner="National Public Radio",
        state_media=True,
        based="US",
    ),
    # Sky News
    NewsSource(
        source="Sky News",
        name="Sky News",
        url="https://feeds.skynews.com/feeds/rss/home.xml",
        bias="center",
        owner="Comcast",
        state_media=False,
        based="UK",
    ),
    # The Telegraph
    NewsSource(
        source="The Telegraph",
        name="The Telegraph",
        url="https://www.telegraph.co.uk/rss.xml",
        bias="right",
        owner="Telegraph Media Group",
        state_media=False,
        based="UK",
    ),
    # Yahoo News
    NewsSource(
        source="Yahoo News",
        name="Yahoo News",
        url="https://news.yahoo.com/rss/",
        bias="center",
        owner="Yahoo",
        state_media=False,
        based="US",
    ),
]

def get_news_sources() -> List[NewsSource]:
    pass